apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-data-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-data
  template:
    metadata:
      labels:
        app: shared-data
    spec:
      volumes:
        - name: shared-data-volume
          persistentVolumeClaim:
            claimName: example-pvc
      containers:
        - name: busybox
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - >
              while true;
              do echo "$(date) - Data written by busybox" >> /data/shared-file.txt;
              sleep 5;
              done;
          volumeMounts:
            - name: shared-data-volume
              mountPath: /data
        - name: multitool
          image: wbitt/network-multitool:latest
          command:
            - /bin/sh
            - -c
            - >
              while true;
              do cat /data/shared-file.txt;
              sleep 5;
              done;
          volumeMounts:
            - name: shared-data-volume
              mountPath: /data
